### ISSUE TITLE
Cant launch backend

### ISSUE THREAD

**Issue by ghost** [VVoiddd/Momentum-Vbucks-On-Kill-V2#1]
when i launched it it gave me this error i have installed all packages and ran install.bat
![Capture](https://github.com/VVoiddd/Momentum-Vbucks-On-Kill-V2/assets/143820445/abefe80b-fada-4669-8c99-6b29b2995dae)

**Comment by VVoiddd** [comment]
i will fix it in a few days if not today, thank you for bringing this to me attention

**Comment by EFFXCT290** [comment]
is it fixed?

**Comment by EFFXCT290** [comment]
i tried to fixed it but doesn't work maybe I did it wrong

**Comment by VVoiddd** [comment]
> is it fixed?



Thank you for reporting the issue you've encountered. Based on the error message you've provided, it appears there's a mismatch in how the `profiles.js` module is being imported in the `functions.js` file. This is a common issue when the import statement doesn't align with the export format of the module. Here's how you can resolve this:

1. **Check the Export in `profiles.js`**:
   - Open the `profiles.js` file located in the `model` directory.
   - Inspect how the module is being exported. If the file uses a named export (like `export { Profile };`), then it cannot be imported using a default import.

2. **Update the Import Statement in `functions.js`**:
   - In the `functions.js` file, update the import statement to match the export type of `profiles.js`.
   - If `profiles.js` uses a named export, modify the import statement to something like this:
     ```javascript
     import { Profile } from '../../model/profiles.js';
     ```
   - Ensure that the import statement correctly reflects whether `Profile` is a default or named export.

3. **Verify File Paths**:
   - Double-check that the file paths in the import statement are correct and that `profiles.js` exists at the specified location.

4. **Rebuild and Restart the Application**:
   - After making the necessary changes, if your project requires building, run the build process again.
   - Restart your application to see if the issue is resolved.

If you've followed these steps and are still experiencing issues, please provide additional details, and I'll be happy to assist further.
